"""empty message

Revision ID: 028e0f12dc16
Revises: 2bd377320658
Create Date: 2025-09-08 23:08:37.120314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028e0f12dc16'
down_revision = '2bd377320658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pict', sa.String(), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=9999), nullable=True))
        batch_op.drop_column('profile_pict')

    # ### end Alembic commands ###
