"""Initial Migration

Revision ID: 314e74ced996
Revises: 
Create Date: 2025-09-07 00:44:07.200405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314e74ced996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aspiring_job', sa.String(length=9999), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('aspiring_job')

    # ### end Alembic commands ###
