"""empty message

Revision ID: 98973df3d2dd
Revises: 40ed72889d7a
Create Date: 2025-09-09 02:06:51.415026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98973df3d2dd'
down_revision = '40ed72889d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
