"""empty message

Revision ID: d5e444518c3d
Revises: 028e0f12dc16
Create Date: 2025-09-08 23:18:50.409125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e444518c3d'
down_revision = '028e0f12dc16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))
        batch_op.drop_column('profile_pict')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pict', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
